grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 5
    verbose: 1
model_selection:
  module_0:
    module: sklearn.ensemble         
    class: RandomForestRegressor    
    params:
      random_state: 42
    search_param_grid:
      n_estimators:
        - 100
        - 200
      max_depth:
        - 5
        - 10
  module_1:
    module: xgboost                 
    class: XGBRegressor             
    params:
      objective: reg:squarederror
    search_param_grid:
      n_estimators:
        - 50
        - 100
      learning_rate:
        - 0.05
        - 0.1